PriceConfig:
  PricePort: 8080

KafkaConfig:
  addresses: ["localhost:9091", "localhost:9092", "localhost:9093"]
  topic: "price"

ProducerConfig:
  tickers: ["AAPL", "GOOG", "TSLA"]
  intervalMs: 5000
  initialPrice: 200.0
  volatilityPercent: 0.5